FROM node:16.14.0-slim

WORKDIR /app

ADD package.json yarn.lock ./
RUN yarn install

COPY . .

CMD [ "bash", "-c" , "./generate_env_config.sh -t env_config_template.js -e public/env.js && yarn start" ]
