#! /bin/bash

while getopts t:e: flag
do
    case "${flag}" in
        t) TEMPLATE_FILE=${OPTARG};;
        e) ENV_FILE=${OPTARG};;
    esac
done

echo "// Auto generated by generate_env_config.sh" > $ENV_FILE
while read p; do
    if [[ $p == *\$\{* ]]
    then
        eval "echo \"${p}\" >> $ENV_FILE"
    else
        echo "${p}" >> $ENV_FILE
    fi
done < $TEMPLATE_FILE