version: '2.4'

services:
  webservice:
    container_name: jit_rec_webservice
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - SSL_ENABLED
      - DEFAULT_DATABASE_URL
      - BACKEND_HOST
      - FRONTEND_HOST
      - RTMP_HOST
      - RTMP_PORT
      - SECRET_KEY
      - DEBUG
      - RECORD_TOKEN_TTL_MINUTES
    command: >
      sh -c "python manage.py migrate & python manage.py runserver 0.0.0.0:8000"
  
  rtmp_server:
    container_name: jit_rec_rtmp_server
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - SSL_ENABLED
      - DEFAULT_DATABASE_URL
      - BACKEND_HOST
      - FRONTEND_HOST
      - RTMP_HOST
      - RTMP_PORT
      - SECRET_KEY
      - DEBUG
      - RECORD_TOKEN_TTL_MINUTES
    command: python manage.py run_rtmp_server --host=0.0.0.0 --port=1935 --workers=${RTMP_WORKERS}
  
  frontend:
    container_name: jit_rec_frontend
    build:
      context: frontend
      dockerfile: ${FRONTEND_DOCKER_FILE:-Dockerfile}
    volumes:
      - ./frontend/:/app/
    environment:
      - BACKEND_HOST
      - SSL_ENABLED

  nginx:
    container_name: jit_rec_nginx
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/http.conf:/etc/nginx/http.conf
      - ./backend/statics:/app/backend/statics
      - ./backend/data/recordings:/app/backend/data/recordings
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:${RTMP_PORT}:${RTMP_PORT}"
    environment:
     - FRONTEND_HOST
     - BACKEND_HOST
     - RTMP_HOST
     - RTMP_PORT
     - BACKEND_INTERNAL_HOSTNAME
     - FRONTEND_INTERNAL_HOSTNAME
     - RTMP_INTERNAL_HOSTNAME
