# Generated by Django 3.2 on 2022-08-07 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
